language: php

env:
  - TRAVISASSUMESWRONGSTUFF=FAIL

matrix:
  include:
    - env: DBTYPE=mysql LANG=de
      php: 5.3
    - env: DBTYPE=mysql LANG=de
      php: 5.4
    - env: DBTYPE=sqlite LANG=de
      php: 5.5
    - env: DBTYPE=sqlite LANG=en
      php: 5.3
    - env: DBTYPE=sqlite LANG=en
      php: 5.4
    - env: DBTYPE=mysql LANG=en
      php: 5.5
  exclude:
    - env: TRAVISASSUMESWRONGSTUFF=FAIL

before_script:
  - bash .travis.sh

script:
  - cd ../phase3/tests/phpunit
  - ./phpunit.php --group Wikibase --log-tap php://stdout --exclude-group WikibaseAPI

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
      - abraham.taherivand@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
