language: php

dist: bionic

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - env: DBTYPE=sqlite LANG=ru WB=both
      php: 7.3.19
    - env: DBTYPE=sqlite LANG=en WB=client
      php: 7.3.19
    - env: DBTYPE=mysql LANG=en WB=repo
      php: 7.3.19
    - env: DBTYPE=sqlite LANG=ar WB=both
      php: 7.3.19
    - env: DBTYPE=mysql LANG=en WB=both
      php: 7.3.19

before_script:
    - bash ./build/travis/install.sh
    - bash ./build/travis/mw-apply-wb-settings.sh
    - bash ./build/travis/update-db.sh

script:
    - bash ./build/travis/script.sh

notifications:
  email:
    recipients:
      - wikidata-ci-status@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
