language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql LANG=de; MW=master WB=client
      php: 5.3
    - env: DBTYPE=sqlite LANG=de; MW=master WB=repo
      php: 5.3
    - env: DBTYPE=sqlite LANG=de; MW=master WB=both
      php: 5.4
    - env: DBTYPE=sqlite LANG=en; MW=master WB=client
      php: 5.5
    - env: DBTYPE=mysql LANG=en; MW=master WB=repo
      php: 5.6
    - env: DBTYPE=sqlite LANG=en; MW=master WB=both
      php: hhvm
  allow_failures:
    - php: hhvm
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script:
    - bash ./build/travis/install.sh
    - bash ./build/travis/mw-apply-wb-settings.sh
    - bash ./build/travis/update-db.sh

script:
    - bash ./build/travis/script.sh

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
      - abraham.taherivand@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
