language: php

matrix:
  include:
    - env: DBTYPE=mysql EXTENSION=client
      php: 5.3
    - env: DBTYPE=mysql EXTENSION=client
      php: 5.4
    - env: DBTYPE=sqlite EXTENSION=client
      php: 5.5
    - env: DBTYPE=sqlite EXTENSION=repo
      php: 5.3
    - env: DBTYPE=sqlite EXTENSION=repo
      php: 5.4
    - env: DBTYPE=mysql EXTENSION=repo
      php: 5.5
    - env: DBTYPE=postgres EXTENSION=repo
      php: 5.5
  allow_failures:
    - env: DBTYPE=postgres EXTENSION=repo

before_script:
  - bash .travis.sh $EXTENSION

script:
  - cd ../phase3/tests/phpunit
  - ./phpunit.php --group Wikibase

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always